=head1 TABLE OF CONTENTS

This is a list of documents relating to the Java JVM 
=> Parrot Intermediate Representation translator.

=head2 USING THE TRANSLATOR

=over 4

=item L<introduction.pod>: Introduction

=item L<building.pod>: Building

=item L<running.pod>: Running the class => PBC translator

=item L<pirinterface.pod>: Loading Java classes directly from PIR code

=back

=head2 HACKING ON THE TRANSLATOR

=over 4

=item L<overview.pod>: Overview of the system

=item L<pmcs.pod>: The Java metadata PMCs

=item L<metadatatranslator.pod>: Translating Java class metadata to PIR

=back

=head2 CONSTRUCT TRANSLATION DETAILS

=item L<../languages/dotnet/doc/contents.pod>: dotnet details

=item L<../../lib/SRM/doc/rulesfile.pod>: The rules file

=item L<../../lib/SRM/doc/translatorbuilder.pod>: The translator builder

=item L<../../lib/SRM/doc/stacktoregister.pod>: Notes on stack to register mapping


=head2 FURTHER REFERENCES

=over 4

=item L<http://java.sun.com/docs/books/vmspec/2nd-edition/html/VMSpecTOC.doc.html>: 
vmspec 2nd edition online

=item L<http://en.wikipedia.org/wiki/Java_Virtual_Machine>: JVM on Wikipedia

=item L<http://www.jnthn.net/papers/2006-cam-net2pir-dissertation.pdf>: 
J.Worthington's Dissertation Paper on net2pbc

=back

=cut

# Local Variables:
#   fill-column:78
# End:
# vim: expandtab shiftwidth=4:
