=head1 Running

This document describes how to use the command line class2pbc program, which
converts a Java class or jar file into a Parrot Bytecode file (or optionally dumps
the PIR generated in the process).


=head2 Usage

To translate example.class to example.pbc:

  parrot class2pbc.pbc example.class

To translate example.class to output.pbc:

  parrot class2pbc.pbc -o output.pbc example.class

To translate example.class to PIR and print the PIR:

  parrot class2pbc.pbc -p example.class

This works just the same with jar files.

A number of additional flags are available:

  -f  Force translation to continue, even if translating a certain
      type fails.
  -t  Trace the translation process, producing useful debug info.
  -q  Quiet mode; suppress output of summary at the end.

